CREATE SCHEMA IF NOT EXISTS 'film_library'
CREATE TABLE Films (
	F_ID INT AUTO_INCREMENT PRIMARY KEY,
	F_Name VARCHAR(100),
    F_Producer VARCHAR(40),
    F_Director VARCHAR(40),
    F_Prizes INT,
    F_Copies INT,
    F_Ratings INT,
    F_Type VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS Actors (
	A_ID INT AUTO_INCREMENT PRIMARY KEY,
	A_Name VARCHAR(100)
	A_Gender VARCHAR(6)
);
CREATE TABLE IF NOT EXISTS FilmCast (
	F_ID INT,
	A_ID INT,
	FC_Role VARCHAR(40),
	FOREIGN KEY (F_ID) REFERENCES Films(F_ID),
    FOREIGN KEY (A_ID) REFERENCES Actors(A_ID)
);
CREATE TABLE IF NOT EXISTS Customers (
	C_ID INT AUTO_INCREMENT PRIMARY KEY,
	C_Name VARCHAR(100),
    C_SubType VARCHAR(20),
    C_PaymentMethod VARCHAR(20),
    C_Debt INT
);
CREATE TABLE IF NOT EXISTS LibraryEmployees (
	LE_ID INT AUTO_INCREMENT PRIMARY KEY,
	LE_Name VARCHAR(100),
    LE_Role VARCHAR(20),
    LE_Salary INT,
    LE_Years_Worked INT
);
CREATE TABLE IF NOT EXISTS FilmRentals (
	FR_ID INT AUTO_INCREMENT PRIMARY KEY,
	F_ID INT,
    C_ID INT,
	FR_WhenRented DATETIME,
    FR_WhenReturned DATETIME,
    FR_ConditionBeforeRented VARCHAR(20),
    FR_ConditionWhenReturned VARCHAR(20),
    LE_ID INT
    FOREIGN KEY (F_ID) REFERENCES Films(F_ID),
    FOREIGN KEY (C_ID) REFERENCES Customers(C_ID),
    FOREIGN KEY (LE_ID) REFERENCES LibraryEmployees(LE_ID)
);
CREATE TABLE IF NOT EXISTS Shifts (
	S_DateAndTime DATETIME,
	LE_ID INT,
    FOREIGN KEY (LE_ID) REFERENCES LibraryEmployees(LE_ID)
);