CREATE SCHEMA IF NOT EXISTS 'film_library'
CREATE TABLE IF NOT EXISTS Films (
	F_ID INT AUTO_INCREMENT PRIMARY KEY,
	F_Name VARCHAR(100),
    F_Producer VARCHAR(40),
    F_Director VARCHAR(40),
    F_Prizes INT,
    F_Year INT,
    F_Ratings INT,
    F_Type VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS Actors (
	A_ID INT AUTO_INCREMENT PRIMARY KEY,
	A_Name VARCHAR(100)
	A_Gender VARCHAR(6)
);
CREATE TABLE IF NOT EXISTS FilmCast (
	F_ID INT,
	A_ID INT
	FOREIGN KEY (F_ID) REFERENCES Films(F_ID),
    FOREIGN KEY (A_ID) REFERENCES Actors(A_ID)
);
CREATE TABLE IF NOT EXISTS Users (
	C_ID INT AUTO_INCREMENT PRIMARY KEY,
	C_Username VARCHAR(100),
    C_Password VARCHAR(100)
);