pipeline {
    agent {
        kubernetes {
        label 'agent-app'
        yamlFile 'build-pod.yaml'
        defaultContainer 'ez-docker-helm-build'
        }
    }

    environment {
        DOCKER_IMAGE_NAME = "itsvictorfy/final-proj"
        DOCKER_IMAGE_TAG = "${env.GIT_COMMIT.take(5)}"
        DOCKERHUB_USERNAME = credentials('victor_dockerhub_username')
        DOCKERHUB_PASS = credentials('victor_dockerhub_pass')
    }


    stages {
        stage('Build image') {
            steps {
                echo 'Starting to build docker image'
                 sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ."
            }
        }
        stage('Build Helm Chart') {
            steps {
                sh 'helm lint movie-lib-app-chart'
                sh 'helm package movie-lib-app-chart --version '+ DOCKER_IMAGE_TAG
            }
        }
        stage('Push Docker image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'victor_dockerhin_user') {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Push HELM chart') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'victor_dockerhin_user', passwordVariable:'DOCKERHUB_PASSWORD',usernameVariable: 'DOCKERHUB_USER')]) {
                        sh "docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}"
                        sh 'helm push movie-lib-app-chart-'+ DOCKER_IMAGE_TAG+'.tgz oci://registry-1.docker.io/films-lib'
                    }
                }
            }
        }
    }
}
