# Default values for film-library-app.
namespace: test  # Replace 'default' with the desired namespace

replicaCount: 2  # Replace '3' with the desired number of replicas

image:
  repository: itsvictorfy/film-library-app
  tag: V0.01
  pullPolicy: IfNotPresent
spec:
  replicaCount: 2

service:
  type: LoadBalancer
  port: 8080

database:
  host: your_database_host
  database: film_library
  user: your_database_username
  password: your_database_password
