# Default values for film-library-app.
namespace: stage  # Replace 'default' with the desired namespace

replicaCount: 2  # Replace '3' with the desired number of replicas

image:
  repository: itsvictorfy/final-proj
  tag: aca930b
  pullPolicy: IfNotPresent
spec:
  replicaCount: 2

service:
  type: LoadBalancer
  port: 8080

database:
  host: postgres
  database: moviesDB
  user: admin
  password: sqlAdmin
