apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: "film-application"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: "film-application"
