# Jenkins & ArgoCD
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-ingress
  namespace: cicd
  annotations:
    # cert-manager.io/cluster-issuer: "base-issuer" # SSL certificates issuer - you don't need it if you don't use SSL
    # nginx.ingress.kubernetes.io/proxy-body-size: "200m" # If you need to upload big files
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # You can check it with kubectl get ingressclass
  ingressClassName: nginx
  rules:
    - host: ingress-nginx-controller # Update this to your actual host
      http:
        paths:
        - pathType: Prefix
          path: /ci(/|$)(.*)
          # https://XXX.XXX.XXX.XXX/ci - (/|$) - means that it can be /ci or /ci/,
          # (.*) - means that it can be /ci/ or /ci/anything,
          # $2 in the rewrite-target annotation will be translated to /anything in the request to backend service01/anything
          backend:
            service:
              name: jenkins
              port:
                number: 8080
        - pathType: Prefix
          path: /cd(/|$)(.*)
          backend:
            service:
              name: argocd
              port:
                number: 443
---
# Prometheus & Grafana
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observation-ingress
  namespace: observation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ingress-nginx-controller # Update this to your actual host
      http:
        paths:
        - pathType: Prefix
          path: /monitor(/|$)(.*)
          backend:
            service:
              name: prometheus
              port:
                number: 9090
        - pathType: Prefix
          path: /observe(/|$)(.*)
          backend:
            service:
              name: grafana
              port:
                number: 3000



###### No database URI since its non http service and therefore not supported by ingress