apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd
spec:
  rules:
    - host: victor-final.proj
      http:
        paths:
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
az network dns record-set a add-record \
    --resource-group rg-finalproj \
    --zone-name victor-final.proj \
    --record-set-name "*" \
    --ipv4-address 20.4.194.80