apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: cicd
  annotations:
    # cert-manager.io/cluster-issuer: "base-issuer" # SSL certificates issuer - you don't need it if you don't use SSL
    # nginx.ingress.kubernetes.io/proxy-body-size: "200m" # If you need to upload big files
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # You can check it with kubectl get ingressclass
  ingressClassName: nginx
  rules:
    - host: ingress-nginx-controller
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /jenkins(/|$)(.*)
          # https://XXX.XXX.XXX.XXX/jenkins - (/|$) - means that it can be /jenkins or /jenkins/,
          # (.*) - means that it can be /jenkins/ or /jenkins/anything,
          # $2 in the rewrite-target annotation will be translated to /anything in the request to backend service01/anything
          backend:
            service:
              name: jenkins
              port:
                number: 8080

