apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: http://20.73.139.100  # Replace with your domain or IP address
      http:
        paths:
          - pathType: Prefix
            path: /grafana
            backend:
              service:
                name: grafana
                port:
                  number: 80
          - pathType: Prefix
            path: /argo
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
          - pathType: Prefix
            path: /jenkins
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: movies-victor
  namespace: monitoring
spec:
  type: ExternalName
  externalName: movies-victor