apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: db-persistent-volume-claim
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
