apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: {{ .Values.dbName | b64enc | quote }}
  POSTGRES_USER: {{ .Values.dbUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.dbPassword | b64enc | quote }}